events {
    worker_connections 1024;
}

http {
    upstream backend_servers {
        server sitio1:80;
        server sitio2:80;
        server sitio3:80;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backend_servers;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Cache-Control "no-cache, no-store, must-revalidate";
            add_header Cache-Control "no-cache, no-store, must-revalidate";
            add_header X-Upstream-Server $upstream_addr;
        }
    }
}