# #Capa 1: Imagen base
# FROM ubuntu:latest

# #Capa 2: Actualizar el sistema e instalar dependencias
# RUN apt-get update

# #Capa 3: Instalar curl
# RUN apt-get install -y curl

# #Capa 4: Copia el contenido del directorio actual a /app
# COPY . /app

# #capa 5: Ejecuta un comando de terminal
# CMD [ "echo", "Hello, World!" ]



#Capa 1: Imagen base
FROM ubuntu:20.04

#Capa 2: Actualizar el sistema e instalar dependencias
RUN apt-get update && \
    apt-get install -y curl && \
    rm -rf /var/lib/apt/lists/* 

#Capa 4: Copia el contenido del directorio actual a /app
COPY . /app

#capa 5: Ejecuta un comando de terminal
CMD [ "echo", "Hello, World!" ]